### ISSUE TITLE
home navigation was added

### ISSUE THREAD

**Issue by cristian-programmer** [skift-org/website#1]
you can watch the changes here: [repo](https://github.com/cristian-programmer/skiftos.github.io/tree/gh-pages)
I removed the property of css "position sticky", because it gives problems when it takes me to each of the elements.

Should we add the new kernel information?

**Comment by sleepy-monax** [comment]
Look good, can you do a pull request so I can review it :)

**Comment by cristian-programmer** [comment]
yes I will do it
